# Generated by Django 4.2.7 on 2026-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="utr_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
