# Generated by Django 4.2.7 on 2026-03-20 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_team_utr_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits and start with 6-9.",
                        regex="^[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
    ]
