# Generated by Django 4.2.7 on 2026-03-20 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_alter_teammember_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="college_code",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="College code must contain only capital letters.",
                        regex="^[A-Z]+$",
                    )
                ],
            ),
        ),
    ]
