# Generated by Django 4.2.7 on 2026-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0004_alter_teammember_college_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="payment_proof",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
