# Generated by Django 4.2.7 on 2026-04-19 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0005_alter_team_payment_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="utr_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="college_code",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="College code must contain only capital letters and numbers.",
                        regex="^[A-Z0-9]+$",
                    )
                ],
            ),
        ),
    ]
